# This is a basic workflow to help you get started with Actions

name: MAJ-DEV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Stop
        run: docker stop asd
      - name: Del
        run: docker rm asd
      - name: Pull git
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t asd:docker .
      - name: Start docker
        run: docker run --name asd -d -p 80:80 asd:docker 