# This is a basic workflow to help you get started with Actions

name: MAJ-DEV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "dev" ]
  #pull_request:
    #branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Regarde si la branche est 'dev'
        run: |
          if [ "$GITHUB_REF" = "refs/heads/dev" ]; then
            echo "La branche est 'dev', workflow access."
          else
            echo "La branche n'est pas 'dev', workflow access denied."
            exit 1
          fi
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Initialisation du contenu de la branche
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
      - run: |
          npm install express
          RUNNER_TRACKING_ID="" && nohup sudo node index.js &
